// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getFeaturesByLayerSeriesAndBbox = `-- name: GetFeaturesByLayerSeriesAndBbox :many
select loc.id, loc.name, ST_AsGeoJSON(ST_SimplifyPreserveTopology(loc.geom, $8))::json as geom, val.value
from locations loc
    join values val on loc.id = val.location
where loc.type = $1
    and val.series = $2
    and val.time = $3
    and ST_Intersects(geom, ST_MakeEnvelope($4, $5, $6, $7, 4326))
`

type GetFeaturesByLayerSeriesAndBboxParams struct {
	Type                       LocationType
	Series                     string
	Time                       time.Time
	StMakeenvelope             interface{}
	StMakeenvelope_2           interface{}
	StMakeenvelope_3           interface{}
	StMakeenvelope_4           interface{}
	StSimplifypreservetopology interface{}
}

type GetFeaturesByLayerSeriesAndBboxRow struct {
	ID    string
	Name  string
	Geom  json.RawMessage
	Value sql.NullFloat64
}

func (q *Queries) GetFeaturesByLayerSeriesAndBbox(ctx context.Context, arg GetFeaturesByLayerSeriesAndBboxParams) ([]GetFeaturesByLayerSeriesAndBboxRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturesByLayerSeriesAndBbox,
		arg.Type,
		arg.Series,
		arg.Time,
		arg.StMakeenvelope,
		arg.StMakeenvelope_2,
		arg.StMakeenvelope_3,
		arg.StMakeenvelope_4,
		arg.StSimplifypreservetopology,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturesByLayerSeriesAndBboxRow
	for rows.Next() {
		var i GetFeaturesByLayerSeriesAndBboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Geom,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
