// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/twpayne/go-geom"
)

type LocationType string

const (
	LocationTypeKraj LocationType = "kraj"
	LocationTypeOrp  LocationType = "orp"
	LocationTypeObec LocationType = "obec"
)

func (e *LocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationType(s)
	case string:
		*e = LocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationType: %T", src)
	}
	return nil
}

type NullLocationType struct {
	LocationType LocationType
	Valid        bool // Valid is true if LocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationType) Scan(value interface{}) error {
	if value == nil {
		ns.LocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationType), nil
}

type Location struct {
	ID     string
	Name   string
	Type   LocationType
	Parent sql.NullString
	Geom   geom.T
}

type Series struct {
	ID          string
	Name        string
	Unit        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Value struct {
	Series   string
	Location string
	Time     time.Time
	Value    sql.NullFloat64
}
